### ISSUE TITLE
Bots stuck!!!!!!

### ISSUE THREAD

**Issue by Limitbreaker1116** [AALUND13/RoundsWithBots#1]
Sometimes, the bots get stuck in place and do not pursue each other if the player is already dead. Since there isn't a reset or skip feature for the current round, the whole deathmatch game needs to be restarted.

**Comment by AALUND13** [comment]
Thank you for the bug report! I've been aware of this bug for a while now. I might be able to fix it by starting a timer when the player dies. Once the timer reaches zero, it will slowly kill the bots.

**Comment by AALUND13** [comment]
@Limitbreaker1116 This bugs have be fixed, I added stalemate handler, So If the player is dead for a set amount of time, the stalemate handler triggers, gradually killing the bots to end the round.

**Comment by Limitbreaker1116** [comment]
Wow, that was incredibly fast! I'll try it out later, thank you!
